version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}apilistadecompra
    build:
      context: src/ApiListaDeCompra
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
